### ISSUE TITLE
Selection (highlighting) happening on gesture

### ISSUE THREAD

**Issue by adammenges** [bmcmahen/react-gesture-view#8]
![Kapture 2019-05-20 at 15 29 24](https://user-images.githubusercontent.com/817438/58056099-cec39f80-7b14-11e9-9663-d4ff05468f28.gif)
A selection happens when preforming a gesture. Notice the green along the edge (my highlight color on my computer). As I was testing, all div's involved have the following no-selection css applied:

``` css
.noselect {
  -webkit-touch-callout: none; /* iOS Safari */
  -webkit-user-select: none; /* Safari */
  -khtml-user-select: none; /* Konqueror HTML */
  -moz-user-select: none; /* Firefox */
  -ms-user-select: none; /* Internet Explorer/Edge */
  user-select: none; /* Non-prefixed version, currently supported by Chrome and Opera */
}
```

It also disappears after a second, which I assume happens after the animation is considered done. Here's the full component to repo this, I just made a simple reate-create-app to play around with this package.

``` js
import React from 'react'
import GestureView from 'react-gesture-view'

export const Project = () => {
  const [index, setIndex] = React.useState(0)
  const size = useWindowSize()
  const small = size.width <= 640

  const project1 = (
    <div
      style={{
        width: 500,
        height: 400,
        backgroundColor: '#111',
        color: '#FFF',
      }}
      className="noselect"
    >
      <div className="noselect">something111</div>
    </div>
  )
    
  const project2 = (
    <div
      style={{
        width: 500,
        height: 400,
        backgroundColor: '#777',
        color: '#FFF',
      }}
      className="noselect"
    >
      <div className="noselect">something222</div>
    </div>
  )

  const desktop = (
    <div
      style={{
        width: 500,
        height: 400,
        backgroundColor: '#555',
        color: '#FFF',
      }}
      className="noselect"
    >
      <GestureView
        value={index}
        enableMouse={true}
        onRequestChange={i => setIndex(i)}
      >
        {project1}
        {project2}
      </GestureView>
    </div>
  )
  return (
    <div style={{ position: 'relative' }} className="noselect">
      {desktop}
    </div>
  )
}
```

**Comment by bmcmahen** [comment]
Hey @adammenges, thanks for the detailed issue writeup.

I'm pretty sure this is actually the `outline` property being set for accessibility reasons. I'm not entirely sure how to handle accessibility for a component like this, but I suspect the outline might not be necessary since focus is automatically handled. 

So, in short, to remove the outline use `outline: none` in your css.

**Comment by bmcmahen** [comment]
I think I can get away with removing the outline. I'll post a new release soon where this is the default behaviour.

**Comment by adammenges** [comment]
Awesome, thanks! I'll try this out later today.

**Comment by adammenges** [comment]
Bummer, I still see the issue even with `outline: none;`

<img width="1280" alt="Screen Shot 2019-05-23 at 8 08 32 PM" src="https://user-images.githubusercontent.com/817438/58300261-b498f400-7d96-11e9-9882-26dfcc5ca5b0.png">

[Kapture.zip](https://github.com/bmcmahen/react-gesture-view/files/3214904/Kapture.zip) (just a .mp4 but github wanted a zip file instead)

**Comment by adammenges** [comment]
If you'd like to see play around in that storybook: https://github.com/adammenges/adammengesWebsite

I also noticed on Safari there's an audible sound when you move between views, perhaps also because of accessibility reasons.

**Comment by bmcmahen** [comment]
Ah, it's because the gesture view actually wraps your div with its own element and this is where the focusing is happening. I'm going to push a new release that removes this outline & will let you know when it's up.

**Comment by bmcmahen** [comment]
Okay, try version 2.1.1. It should do the trick. 

I'm not sure about the sound from Safari. Is this mobile safari? Desktop?

**Comment by adammenges** [comment]
Desktop safari, I can get you the version number or whatever else you’d like if it’s hard to repo on your end.

**Comment by adammenges** [comment]
2.1.1 did the trick for the outline, thanks!

**Comment by adammenges** [comment]
For what it's worth, for future folks who search here, the beeping is safari is still there, and at least for you personally you can turn it off with: https://superuser.com/questions/98868/how-do-i-disable-the-beep-in-osx-leopard-when-i-perform-an-invalid-action

It's worth noting I haven't ever seen other carrousel type gesture interfaces with this beep. For instance: http://brandonwalkin.com doesn't have any issues.

**Comment by bmcmahen** [comment]
So strange! Let me see if I can fix this

**Comment by bmcmahen** [comment]
@adammenges I'm unable to replicate this in Safari. Does it only occur when dragging your mouse?

Can you try the example on this page to see if it still makes the sound? (swipe up, and then swipe left / right to switch between icon sets) https://react-gesture-responder.netlify.com

Which version of Safari / Mac OS are you running? I'm actually using the new Mac OS beta with Safari 13.0, so maybe that fixed it?

**Comment by adammenges** [comment]
Yeah let's see, I'm on: Safari Version 12.1 (14607.1.40.1.4), and
macOS 10.14.4 (18E226)

And weird, I'm not hearing it on that example. I wonder what's different
with my little POC. It's pretty basic, not a lot going on there.

**Comment by adammenges** [comment]
Ah, and yeah, only when I drag my mouse.

**Comment by bmcmahen** [comment]
I'm messing around with your repo and can't seem to replicate it there either. Hrrmm. 

Maybe try setting user-select: none?

**Comment by adammenges** [comment]
When you're playing around in the repo did you check out storybook? That's the only place where there's visible react-gesture-view-ness going on.

For good measure, every one of the `GestureView` children has the noselect class:

``` css
.noselect {
  -webkit-touch-callout: none; /* iOS Safari */
  -webkit-user-select: none; /* Safari */
  -khtml-user-select: none; /* Konqueror HTML */
  -moz-user-select: none; /* Firefox */
  -ms-user-select: none; /* Internet Explorer/Edge */
  user-select: none; /* Non-prefixed version, currently supported by Chrome and Opera */
}
```
